### ISSUE TITLE
Aborted due to failure (Wrong size for extra data)

### ISSUE THREAD

**Issue by polluxau** [flathub/com.obsproject.Studio.Plugin.DistroAV#1]
> [!IMPORTANT]  
> **Word from the maintainer: If it happens again, post a comment here rather than opening another issue**

-----------------------------------------------------------------------------------------------------------------------------------------------------------------

trying to download the plugin through discover i get this error 

Aborted due to failure (Wrong size for extra data https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz)

same error when trying to install through terminal

error: Failed to install com.obsproject.Studio.Plugin.NDI: Wrong size for extra data https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v5_Linux.tar.gz

opensuse tumbleweed
plasma 5.27.9

**Comment by lateensl** [comment]
This problem seems to be happening again

`error: Failed to install com.obsproject.Studio.Plugin.DistroAV: Wrong size for extra data https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v6_Linux.tar.gz`

installed through the terminal on Void Linux

**Comment by tytan652** [comment]
NDI SDK updated.

**Comment by pvpcaleium** [comment]
@tytan652 

I tried today to run the following command to install via flatpak

`flatpak install com.obsproject.Studio com.obsproject.Studio.Plugin.DistroAV`
I am seeing the following error

> Failed to install com.obsproject.Studio.Plugin.DistroAV: Wrong size for extra data https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v6_Linux.tar.gz

I am not sure how to get this to pull the latest version of the changes that have been made. 

Thanks

**Comment by ShovelwareDev** [comment]
Same issue with the Flatpak

Rocky 10 / KDE and Flatpak OBS
